require("plug_config.nvim-lspconfig")
require("plug_config.nvim-tree")
require("plug_config.telescope")
require("plug_config.whick-key-nvim")
require("plug_config.nvim-cmp")
require("plug_config.barbar-nvim")
require("plug_config.mason")
